### ISSUE TITLE
pyaudi install. ImportError: dynamic module does not define init function (init_core)

### ISSUE THREAD

**Issue by delvillarfr** [darioizzo/audi#24] opened 2017-10-09 18:24 UTC
Thank you for the heads-up regarding pip install pyaudi. Unfortunately I am still running into problems when installing from source.

After installing the dependencies (boost C++ libraries, MPFR, GMP, piranha), I followed the steps:
```
$ git clone https://github.com/darioizzo/audi.git
$ mkdir ./audi/build
$ cd ./audi/build
$ cmake -DBUILD_PYAUDI=ON -DBUILD_TESTS=ON ../
$ make
$ make test
$ sudo make install
```

Running the command `import pyaudi ` returns the error message
```
/usr/local/lib/python2.7/site-packages/pyaudi/__init__.py in <module>()
      1 __all__ = ['test']
----> 2 from ._core import *
      3 
      4 __version__ = {'major': 1, 'minor': 0, 'bugfix': 3}

ImportError: dynamic module does not define init function (init_core)
```
The solutions to this type of error I could find don't seem to shed light in this case... Is there any brief guidance you could provide?

**Comment by darioizzo** [comment] 2017-10-10 08:02
This is related to a bug in boost libraries with version >1.64 (not sure they will fix it). In 3969ee0be6327bee2d813cfcf80b0b690b98fcf5 I applied a patch suggested by @bluescarni  which seems to do the job. 

Can you pull the latest version and recompile and let us know if the problem is fixed?

**Comment by delvillarfr** [comment] 2017-10-10 13:28
Thank you very much!
pyaudi is now successfully imported with the new version.

F

**Comment by darioizzo** [comment] 2017-10-10 13:33
Nice! Thanks for the report. Closing this.

**Closed by darioizzo** 2017-10-10 13:33 UTC
Labels: bug
