### ISSUE TITLE
io header undefined templates

### ISSUE THREAD

**Issue by mikeheddes** [darioizzo/audi#39] opened 2019-04-13 13:20 UTC
With the following include statements and usage of `audi::stream` the compiler error shown bellow occurs.
```cpp
#include <audi/gdual.hpp>
#include <audi/io.hpp>
...
audi::stream(...)
```

```
In file included from PATH/dcgp/tests/compute_perf.cpp:2:
In file included from PATH/dcgp/venv/include/audi/io.hpp:15:
PATH/dcgp/venv/include/audi/exceptions.hpp:23:23: error:
      no template named 'decay_t'; did you mean 'std::decay_t'?
    using line_type = decay_t<decltype(__LINE__)>;
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1309:22: note:
      'std::decay_t' declared here
template <class _Tp> using decay_t = typename decay<_Tp>::type;
                     ^
In file included from PATH/dcgp/tests/compute_perf.cpp:2:
In file included from PATH/dcgp/venv/include/audi/io.hpp:15:
PATH/dcgp/venv/include/audi/exceptions.hpp:27:44: error:
      no template named 'enable_if_t'; did you mean 'std::enable_if_t'?
    template <typename... Args, typename = enable_if_t<std::is_constructible<Exception, A...

                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:427:39: note:
      'std::enable_if_t' declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
                                      ^
In file included from PATH/dcgp/tests/compute_perf.cpp:2:
In file included from PATH/dcgp/venv/include/audi/io.hpp:15:
PATH/dcgp/venv/include/audi/exceptions.hpp:35:67: error:
      no template named 'decay_t'; did you mean 'std::decay_t'?
                                                 && (std::is_same<decay_t<Str>, std::stri...
                                                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1309:22: note:
      'std::decay_t' declared here
template <class _Tp> using decay_t = typename decay<_Tp>::type;
                     ^
In file included from PATH/dcgp/tests/compute_perf.cpp:2:
In file included from PATH/dcgp/venv/include/audi/io.hpp:15:
PATH/dcgp/venv/include/audi/exceptions.hpp:36:70: error:
      no template named 'decay_t'; did you mean 'std::decay_t'?
                                                     || std::is_same<decay_t<Str>, char *>::value
                                                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1309:22: note:
      'std::decay_t' declared here
template <class _Tp> using decay_t = typename decay<_Tp>::type;
                     ^
In file included from PATH/dcgp/tests/compute_perf.cpp:2:
In file included from PATH/dcgp/venv/include/audi/io.hpp:15:
PATH/dcgp/venv/include/audi/exceptions.hpp:37:70: error:
      no template named 'decay_t'; did you mean 'std::decay_t'?
                                                     || std::is_same<decay_t<Str>, const ...
                                                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1309:22: note:
      'std::decay_t' declared here
template <class _Tp> using decay_t = typename decay<_Tp>::type;
                     ^
5 errors generated.
```

When I replace the includes to the combined audi header the error goes away.
```diff
- #include <audi/gdual.hpp>
- #include <audi/io.hpp>
+ #include <audi/audi.hpp>
...
audi::stream(...)
```

I think some header that is included before `audi/exceptions.hpp` changes the global scope so that `decay_t` and `enable_if_t` are defined.

Note that `PATH` was not in the actual error but I substituted it because it doesn't have any importance to the error itself.

**Comment by mikeheddes** [comment] 2019-04-13 15:23
After some investigation I think the header `audi/back_compatibility.hpp` is missing in `audi/expetions.hpp`. I have not tested if it solves the issue.

**Comment by darioizzo** [comment] 2019-04-13 21:04
Indeed the header should be there .... my guess is that it will effect your issue ...

**Comment by darioizzo** [comment] 2020-01-23 08:36
Closing this as the header is now included. Feel free to reopen if the issue is not solved.

**Closed by darioizzo** 2020-01-23 08:36 UTC
